version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    networks: 
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - postgres
    depends_on: 
      - db
networks: 
  postgres:
    driver: bridge